// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmYz3B6d2J-EDgASNp5hoJ_fSeMgH6B2U',
    appId: '1:125596404673:web:20ea4eb1ff3d5f0b267d40',
    messagingSenderId: '125596404673',
    projectId: 'inventario-blancosgina',
    authDomain: 'inventario-blancosgina.firebaseapp.com',
    storageBucket: 'inventario-blancosgina.firebasestorage.app',
    measurementId: 'G-D7KTSD3RS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnM1jVbxkoPsldhwq3y6D-LAO5c0meKrQ',
    appId: '1:125596404673:android:61d2f03a89f6a3cb267d40',
    messagingSenderId: '125596404673',
    projectId: 'inventario-blancosgina',
    storageBucket: 'inventario-blancosgina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw8DpPjo1xWYpe8Hkf4ZF3X7yWPPEp4hY',
    appId: '1:125596404673:ios:1b211a2c05921bc1267d40',
    messagingSenderId: '125596404673',
    projectId: 'inventario-blancosgina',
    storageBucket: 'inventario-blancosgina.firebasestorage.app',
    iosBundleId: 'com.example.blancosGina',
  );
}
