// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvveAxfC3Dhj9PHk6YzLYHzcLKIVFaQSs',
    appId: '1:131903442796:web:ea2215e8bd923b8752ad49',
    messagingSenderId: '131903442796',
    projectId: 'inventarios-universal',
    authDomain: 'inventarios-universal.firebaseapp.com',
    storageBucket: 'inventarios-universal.firebasestorage.app',
    measurementId: 'G-V6QFZPGHGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfSWKt0Op8ouGuH9SyNB8lkqX6_AqWndM',
    appId: '1:131903442796:android:c684c98675fa972e52ad49',
    messagingSenderId: '131903442796',
    projectId: 'inventarios-universal',
    storageBucket: 'inventarios-universal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhs-ePU3d4femyl2yJVmMZj6GuEPqqE1M',
    appId: '1:131903442796:ios:c28879ea5d22722f52ad49',
    messagingSenderId: '131903442796',
    projectId: 'inventarios-universal',
    storageBucket: 'inventarios-universal.firebasestorage.app',
    iosBundleId: 'com.example.inventariosUniversal',
  );

}